apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wy4m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0029-tenant/ci1t-43256-0029-app/devfile-sample-wy4m@sha256:41e46106a1ef2d4a465e8a9632bd197e22e77cace10524ce41d53ecc6136c105
        name: my-nodejs
        resources: {}
status: {}
