apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wy4m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wy4m
    app.kubernetes.io/part-of: ci1t-43256-0029-app
  name: devfile-sample-wy4m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wy4m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wy4m
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0029-tenant/ci1t-43256-0029-app/devfile-sample-wy4m@sha256:41e46106a1ef2d4a465e8a9632bd197e22e77cace10524ce41d53ecc6136c105
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
